<?php
/**
 * PatchedRule
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hauki API
 *
 * API for the City of Helsinki opening hours database  # Introduction  To do.  # Authentication methods  <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hauki\Model;

use \ArrayAccess;
use \Hauki\ObjectSerializer;

/**
 * PatchedRule Class Doc Comment
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class PatchedRule implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PatchedRule';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'int',
        'group' => 'int',
        'name' => 'string',
        'description' => 'string',
        'context' => 'ContextEnum',
        'subject' => 'SubjectEnum',
        'start' => 'int',
        'frequency_ordinal' => 'int',
        'frequency_modifier' => 'OneOfFrequencyModifierEnumBlankEnumNullEnum',
        'created' => '\DateTime',
        'modified' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'group' => null,
        'name' => null,
        'description' => null,
        'context' => null,
        'subject' => null,
        'start' => null,
        'frequency_ordinal' => null,
        'frequency_modifier' => null,
        'created' => 'date-time',
        'modified' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'group' => 'group',
        'name' => 'name',
        'description' => 'description',
        'context' => 'context',
        'subject' => 'subject',
        'start' => 'start',
        'frequency_ordinal' => 'frequency_ordinal',
        'frequency_modifier' => 'frequency_modifier',
        'created' => 'created',
        'modified' => 'modified'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'group' => 'setGroup',
        'name' => 'setName',
        'description' => 'setDescription',
        'context' => 'setContext',
        'subject' => 'setSubject',
        'start' => 'setStart',
        'frequency_ordinal' => 'setFrequencyOrdinal',
        'frequency_modifier' => 'setFrequencyModifier',
        'created' => 'setCreated',
        'modified' => 'setModified'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'group' => 'getGroup',
        'name' => 'getName',
        'description' => 'getDescription',
        'context' => 'getContext',
        'subject' => 'getSubject',
        'start' => 'getStart',
        'frequency_ordinal' => 'getFrequencyOrdinal',
        'frequency_modifier' => 'getFrequencyModifier',
        'created' => 'getCreated',
        'modified' => 'getModified'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['group'] = $data['group'] ?? null;
        $this->container['name'] = $data['name'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['context'] = $data['context'] ?? null;
        $this->container['subject'] = $data['subject'] ?? null;
        $this->container['start'] = $data['start'] ?? null;
        $this->container['frequency_ordinal'] = $data['frequency_ordinal'] ?? null;
        $this->container['frequency_modifier'] = $data['frequency_modifier'] ?? null;
        $this->container['created'] = $data['created'] ?? null;
        $this->container['modified'] = $data['modified'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['name']) && (mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['start']) && ($this->container['start'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'start', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['start']) && ($this->container['start'] < -2147483648)) {
            $invalidProperties[] = "invalid value for 'start', must be bigger than or equal to -2147483648.";
        }

        if (!is_null($this->container['frequency_ordinal']) && ($this->container['frequency_ordinal'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'frequency_ordinal', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['frequency_ordinal']) && ($this->container['frequency_ordinal'] < 0)) {
            $invalidProperties[] = "invalid value for 'frequency_ordinal', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets group
     *
     * @return int|null
     */
    public function getGroup()
    {
        return $this->container['group'];
    }

    /**
     * Sets group
     *
     * @param int|null $group group
     *
     * @return self
     */
    public function setGroup($group)
    {
        $this->container['group'] = $group;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (!is_null($name) && (mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling PatchedRule., must be smaller than or equal to 255.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets context
     *
     * @return ContextEnum|null
     */
    public function getContext()
    {
        return $this->container['context'];
    }

    /**
     * Sets context
     *
     * @param ContextEnum|null $context context
     *
     * @return self
     */
    public function setContext($context)
    {
        $this->container['context'] = $context;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return SubjectEnum|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param SubjectEnum|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets start
     *
     * @return int|null
     */
    public function getStart()
    {
        return $this->container['start'];
    }

    /**
     * Sets start
     *
     * @param int|null $start start
     *
     * @return self
     */
    public function setStart($start)
    {

        if (!is_null($start) && ($start > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $start when calling PatchedRule., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($start) && ($start < -2147483648)) {
            throw new \InvalidArgumentException('invalid value for $start when calling PatchedRule., must be bigger than or equal to -2147483648.');
        }

        $this->container['start'] = $start;

        return $this;
    }

    /**
     * Gets frequency_ordinal
     *
     * @return int|null
     */
    public function getFrequencyOrdinal()
    {
        return $this->container['frequency_ordinal'];
    }

    /**
     * Sets frequency_ordinal
     *
     * @param int|null $frequency_ordinal frequency_ordinal
     *
     * @return self
     */
    public function setFrequencyOrdinal($frequency_ordinal)
    {

        if (!is_null($frequency_ordinal) && ($frequency_ordinal > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $frequency_ordinal when calling PatchedRule., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($frequency_ordinal) && ($frequency_ordinal < 0)) {
            throw new \InvalidArgumentException('invalid value for $frequency_ordinal when calling PatchedRule., must be bigger than or equal to 0.');
        }

        $this->container['frequency_ordinal'] = $frequency_ordinal;

        return $this;
    }

    /**
     * Gets frequency_modifier
     *
     * @return OneOfFrequencyModifierEnumBlankEnumNullEnum|null
     */
    public function getFrequencyModifier()
    {
        return $this->container['frequency_modifier'];
    }

    /**
     * Sets frequency_modifier
     *
     * @param OneOfFrequencyModifierEnumBlankEnumNullEnum|null $frequency_modifier frequency_modifier
     *
     * @return self
     */
    public function setFrequencyModifier($frequency_modifier)
    {
        $this->container['frequency_modifier'] = $frequency_modifier;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime|null
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime|null $created created
     *
     * @return self
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets modified
     *
     * @return \DateTime|null
     */
    public function getModified()
    {
        return $this->container['modified'];
    }

    /**
     * Sets modified
     *
     * @param \DateTime|null $modified modified
     *
     * @return self
     */
    public function setModified($modified)
    {
        $this->container['modified'] = $modified;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


