<?php
/**
 * ResourceTypeEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hauki API
 *
 * API for the City of Helsinki opening hours database  # Introduction  To do.  # Authentication methods  <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 0.0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hauki\Model;
use \Hauki\ObjectSerializer;

/**
 * ResourceTypeEnum Class Doc Comment
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResourceTypeEnum
{
    /**
     * Possible values of this enum
     */
    const UNIT = 'unit';
    const SECTION = 'section';
    const SPECIAL_GROUP = 'special_group';
    const CONTACT = 'contact';
    const ONLINE_SERVICE = 'online_service';
    const SERVICE = 'service';
    const SERVICE_CHANNEL = 'service_channel';
    const SERVICE_AT_UNIT = 'service_at_unit';
    const RESERVABLE = 'reservable';
    const BUILDING = 'building';
    const AREA = 'area';
    const ENTRANCE_OR_EXIT = 'entrance_or_exit';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNIT,
            self::SECTION,
            self::SPECIAL_GROUP,
            self::CONTACT,
            self::ONLINE_SERVICE,
            self::SERVICE,
            self::SERVICE_CHANNEL,
            self::SERVICE_AT_UNIT,
            self::RESERVABLE,
            self::BUILDING,
            self::AREA,
            self::ENTRANCE_OR_EXIT,
        ];
    }
}


