<?php
/**
 * ResourceStateEnum
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hauki API
 *
 * API for the City of Helsinki opening hours database  # Introduction  To do.  # Authentication methods  <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Hauki\Model;
use \Hauki\ObjectSerializer;

/**
 * ResourceStateEnum Class Doc Comment
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ResourceStateEnum
{
    /**
     * Possible values of this enum
     */
    const OPEN = 'open';
    const CLOSED = 'closed';
    const UNDEFINED = 'undefined';
    const SELF_SERVICE = 'self_service';
    const WITH_KEY = 'with_key';
    const WITH_RESERVATION = 'with_reservation';
    const WITH_KEY_AND_RESERVATION = 'with_key_and_reservation';
    const ENTER_ONLY = 'enter_only';
    const EXIT_ONLY = 'exit_only';
    const WEATHER_PERMITTING = 'weather_permitting';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OPEN,
            self::CLOSED,
            self::UNDEFINED,
            self::SELF_SERVICE,
            self::WITH_KEY,
            self::WITH_RESERVATION,
            self::WITH_KEY_AND_RESERVATION,
            self::ENTER_ONLY,
            self::EXIT_ONLY,
            self::WEATHER_PERMITTING,
        ];
    }
}


