<?php
/**
 * IsOpenNowTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hauki API
 *
 * API for the City of Helsinki opening hours database  # Introduction  To do.  # Authentication methods  <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Hauki\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * IsOpenNowTest Class Doc Comment
 *
 * @category    Class
 * @description IsOpenNow
 * @package     Hauki
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IsOpenNowTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "IsOpenNow"
     */
    public function testIsOpenNow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_open"
     */
    public function testPropertyIsOpen()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resource_timezone"
     */
    public function testPropertyResourceTimezone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resource_time_now"
     */
    public function testPropertyResourceTimeNow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "matching_opening_hours"
     */
    public function testPropertyMatchingOpeningHours()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_timezone"
     */
    public function testPropertyOtherTimezone()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "other_timezone_time_now"
     */
    public function testPropertyOtherTimezoneTimeNow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "matching_opening_hours_in_other_tz"
     */
    public function testPropertyMatchingOpeningHoursInOtherTz()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "resource"
     */
    public function testPropertyResource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
