<?php
/**
 * ResourceStateEnumTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Hauki
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Hauki API
 *
 * API for the City of Helsinki opening hours database  # Introduction  To do.  # Authentication methods  <SecurityDefinitions />
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-beta3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Hauki\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ResourceStateEnumTest Class Doc Comment
 *
 * @category    Class
 * @description ResourceStateEnum
 * @package     Hauki
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ResourceStateEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ResourceStateEnum"
     */
    public function testResourceStateEnum()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
